services:
  database:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: proximaenergia
    volumes:
      - ./proximaenergia.sql:/docker-entrypoint-initdb.d/init.sql